version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - distributed-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  node1:
    build: .
    environment:
      - NODE_ID=node1
      - NODE_HOST=0.0.0.0
      - NODE_PORT=5000
      - CLUSTER_NODES=node1:5000,node2:5001,node3:5002
      - REDIS_HOST=redis
      - METRICS_PORT=9090
    ports:
      - "5000:5000"
      - "9090:9090"
    networks:
      - distributed-net
    depends_on:
      - redis
    volumes:
      - node1-data:/app/data

  node2:
    build: .
    environment:
      - NODE_ID=node2
      - NODE_HOST=0.0.0.0
      - NODE_PORT=5001
      - CLUSTER_NODES=node1:5000,node2:5001,node3:5002
      - REDIS_HOST=redis
      - METRICS_PORT=9091
    ports:
      - "5001:5001"
      - "9091:9091"
    networks:
      - distributed-net
    depends_on:
      - redis
    volumes:
      - node2-data:/app/data

  node3:
    build: .
    environment:
      - NODE_ID=node3
      - NODE_HOST=0.0.0.0
      - NODE_PORT=5002
      - CLUSTER_NODES=node1:5000,node2:5001,node3:5002
      - REDIS_HOST=redis
      - METRICS_PORT=9092
    ports:
      - "5002:5002"
      - "9092:9092"
    networks:
      - distributed-net
    depends_on:
      - redis
    volumes:
      - node3-data:/app/data

networks:
  distributed-net:
    driver: bridge

volumes:
  node1-data:
  node2-data:
  node3-data:
